
language: R
sudo: false
cache: packages

matrix:
  include:
  - r: release
  - r: oldrel
  - r: devel

notifications:
  email:
    recipients:
      - b.skinner@vanderbilt.edu
    on_success: change
    on_failure: change

