# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getDist <- function(xlon, xlat, ylon, ylat, funname) {
    .Call('distweightRcpp_getDist', PACKAGE = 'distweightRcpp', xlon, xlat, ylon, ylat, funname)
}

getDistVec <- function(xlon, xlat, ylon, ylat, funname) {
    .Call('distweightRcpp_getDistVec', PACKAGE = 'distweightRcpp', xlon, xlat, ylon, ylat, funname)
}

invDistWeight <- function(d, exp, transform) {
    .Call('distweightRcpp_invDistWeight', PACKAGE = 'distweightRcpp', d, exp, transform)
}

popDistWMean <- function(fromDF, toDF, measureName, fromID = "unitid", fromYear = "year", fromLonName = "lon", fromLatName = "lat", toLonName = "lon", toLatName = "lat", popName = "pop", distFuncName = "Haversine", distTransform = " ", decay = 2) {
    .Call('distweightRcpp_popDistWMean', PACKAGE = 'distweightRcpp', fromDF, toDF, measureName, fromID, fromYear, fromLonName, fromLatName, toLonName, toLatName, popName, distFuncName, distTransform, decay)
}

distWMean <- function(fromDF, toDF, measureName, fromID = "unitid", fromYear = "year", fromLonName = "lon", fromLatName = "lat", toLonName = "lon", toLatName = "lat", distFuncName = "Haversine", distTransform = " ", decay = 2) {
    .Call('distweightRcpp_distWMean', PACKAGE = 'distweightRcpp', fromDF, toDF, measureName, fromID, fromYear, fromLonName, fromLatName, toLonName, toLatName, distFuncName, distTransform, decay)
}

minDist <- function(fromDF, toDF, fromID = "unitid", fromYear = "year", fromLonName = "lon", fromLatName = "lat", toLonName = "lon", toLatName = "lat", distFuncName = "Haversine") {
    .Call('distweightRcpp_minDist', PACKAGE = 'distweightRcpp', fromDF, toDF, fromID, fromYear, fromLonName, fromLatName, toLonName, toLatName, distFuncName)
}

