# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute distance between each coordinate pair and return matrix
#'
#' @param xlon Vector of longitudes for starting coordinate pairs
#' @param xlat Vector of latitudes for starting coordinate pairs
#' @param ylon Vector of longitudes for ending coordinate pairs
#' @param ylat Vector of latitudes for ending coordinate pairs
#' @param funname String name of distance function: Haversine, Vincenty
#' @return Matrix of distances between each coordinate pair in meters
getDistMat <- function(xlon, xlat, ylon, ylat, funname) {
    .Call('distRcpp_getDistMat', PACKAGE = 'distRcpp', xlon, xlat, ylon, ylat, funname)
}

#' Compute distance between corresponding coordinate pairs and return vector.
#' For use in a data frame.
#'
#' @param xlon Vector of longitudes for starting coordinate pairs
#' @param xlat Vector of latitudes for starting coordinate pairs
#' @param ylon Vector of longitudes for ending coordinate pairs
#' @param ylat Vector of latitudes for ending coordinate pairs
#' @param funname String name of distance function: Haversine, Vincenty
#' @return Vector of distances between each coordinate pair in meters
getDistDF <- function(xlon, xlat, ylon, ylat, funname) {
    .Call('distRcpp_getDistDF', PACKAGE = 'distRcpp', xlon, xlat, ylon, ylat, funname)
}

#' Compute distances between single starting coordinate and vector of
#' ending coordinates.
#'
#' @param xlon Longitude for starting coordinate pair
#' @param xlat Latitude for starting coordinate pair
#' @param ylon Vector of longitudes for ending coordinate pairs
#' @param ylat Vector of latitudes for ending coordinate pairs
#' @param funname String name of distance function: Haversine, Vincenty
#' @return Vector of distances in meters
getDistVec <- function(xlon, xlat, ylon, ylat, funname) {
    .Call('distRcpp_getDistVec', PACKAGE = 'distRcpp', xlon, xlat, ylon, ylat, funname)
}

#' Compute distance between two points.
#'
#' @param xlon Longitude for starting coordinate pair
#' @param xlat Latitude for starting coordinate pair
#' @param ylon Longitude for ending coordinate pair
#' @param ylat Latitude for ending coordinate pair
#' @param funname String name of distance function: Haversine, Vincenty
#' @return Distance in meters
getDist <- function(xlon, xlat, ylon, ylat, funname) {
    .Call('distRcpp_getDist', PACKAGE = 'distRcpp', xlon, xlat, ylon, ylat, funname)
}

#' Compute weighted measures for each coordinate using measures taken at
#' surrounding coordinates. Ending measures are double weighted by population
#' and distance so that surrounding measures taken in nearby areas and those
#' with greater populations are given more weight.
#'
#' @param fromDF DataFrame with coordinates that need weighted measures
#' @param toDF DataFrame with coordinates at which measures were taken
#' @param measureName String name of measure column in toDF
#' @param fromID String name of unique identifer column in fromDF
#' @param fromYear String name of year column in fromDF (assumes multiple years)
#' @param fromLonName String name of column in fromDF with longitude values
#' @param fromLatName String name of column in fromDF with latitude values
#' @param toLonName String name of column in toDF with longitude values
#' @param toLatName String name of column in toDF with latitude values
#' @param popName String name of column in fromDF with population values
#' @param distFuncName String name of distance function: "Haversine" (default) or
#' "Vincenty"
#' @param distTransform String value of distance weight transform: " " (default)
#' or "Log"
#' @param decay Numeric value of distance weight decay: 2 (default)
#' @return Dataframe of population/distance-weighted values
popDistWMean <- function(fromDF, toDF, measureName, fromID = "unitid", fromYear = "year", fromLonName = "lon", fromLatName = "lat", toLonName = "lon", toLatName = "lat", popName = "pop", distFuncName = "Haversine", distTransform = " ", decay = 2) {
    .Call('distRcpp_popDistWMean', PACKAGE = 'distRcpp', fromDF, toDF, measureName, fromID, fromYear, fromLonName, fromLatName, toLonName, toLatName, popName, distFuncName, distTransform, decay)
}

#' Compute distance-weighted measures for each coordinate using measures taken at
#' surrounding coordinates. Ending measures are inverse distance-weighted so that
#' surrounding measures taken in nearby areas are given more weight.
#'
#' @param fromDF DataFrame with coordinates that need weighted measures
#' @param toDF DataFrame with coordinates at which measures were taken
#' @param measureName String name of measure column in toDF
#' @param fromID String name of unique identifer column in fromDF
#' @param fromYear String name of year column in fromDF (assumes multiple years)
#' @param fromLonName String name of column in fromDF with longitude values
#' @param fromLatName String name of column in fromDF with latitude values
#' @param toLonName String name of column in toDF with longitude values
#' @param toLatName String name of column in toDF with latitude values
#' @param distFuncName String name of distance function: "Haversine" (default) or
#' "Vincenty"
#' @param distTransform String value of distance weight transform: " " (default)
#' or "Log"
#' @param decay Numeric value of distance weight decay: 2 (default)
#' @return Dataframe of distance-weighted values
distWMean <- function(fromDF, toDF, measureName, fromID = "unitid", fromYear = "year", fromLonName = "lon", fromLatName = "lat", toLonName = "lon", toLatName = "lat", distFuncName = "Haversine", distTransform = " ", decay = 2) {
    .Call('distRcpp_distWMean', PACKAGE = 'distRcpp', fromDF, toDF, measureName, fromID, fromYear, fromLonName, fromLatName, toLonName, toLatName, distFuncName, distTransform, decay)
}

#' Find minimum distance between starting point and possible end points.
#'
#' @param fromDF DataFrame with coordinates that need weighted measures
#' @param toDF DataFrame with coordinates at which measures were taken
#' @param measureName String name of measure column in toDF
#' @param fromID String name of unique identifer column in fromDF
#' @param fromYear String name of year column in fromDF (assumes multiple years)
#' @param fromLonName String name of column in fromDF with longitude values
#' @param fromLatName String name of column in fromDF with latitude values
#' @param toLonName String name of column in toDF with longitude values
#' @param toLatName String name of column in toDF with latitude values
#' @param distFuncName String name of distance function: "Haversine" (default) or
#' "Vincenty"
#' @return DataFrame with minimum distance in meters
minDist <- function(fromDF, toDF, fromID = "unitid", fromYear = "year", fromLonName = "lon", fromLatName = "lat", toLonName = "lon", toLatName = "lat", distFuncName = "Haversine") {
    .Call('distRcpp_minDist', PACKAGE = 'distRcpp', fromDF, toDF, fromID, fromYear, fromLonName, fromLatName, toLonName, toLatName, distFuncName)
}

